name: Scheduled build

on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build hook on Netlify
      run: curl -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD }}